name: Android CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Test Android Project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '19'

    - name: Cache Gradle files
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle
          
    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew

    - name: Download Dependencies
      run: ./gradlew dependencies

    - name: Run Lint
      run: ./gradlew lint

    - name: Build
      run: ./gradlew assembleDebug

     - name: Run Unit Tests
       run: ./gradlew testDebugUnitTest

     - name: Collect Test Results
       if: always()
       run: |
         mkdir -p junit-reports
         cp -r app/build/test-results/testDebugUnitTest/ junit-reports/

     - name: Upload Test Results
       if: always()
       uses: actions/upload-artifact@v3
       with:
         name: junit-test-results
         path: junit-reports/

    - name: Upload Build Artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/*.apk

    - name: Upload Lint Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: lint-reports
        path: app/build/reports/lint-results*.xml
